apiVersion: kro.run/v1alpha1
kind: IAMController
metadata:
  name: my-kro-iam-controller
  namespace: kro
spec:
  name: ack-iam-controller
  namespace: kro
  values: 
    aws:
      region: us-west-2
    deployment: {}
    image:
      resources:
        requests: {}
        limits: {}
    log:
      enabled: true
      level: debug
    aws: {}
    serviceAccount:
      name: ack-iam-controller-sa
      roleArn: ....
