# values for the addon
deployment:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  nodeSelector:
    eks.amazonaws.com/compute-type: auto
    kubernetes.io/os: linux
    karpenter.sh/nodepool: system
reconcile:
  defaultResyncPeriod: 1800