name: Bug
description: Report a bug
labels:
  - kind/bug
  - needs-triage
body:
  - type: textarea
    attributes:
      label: Description
      value: |
        <!-- Please craft a detailed description of the documentation issue or suggestion -->
        <!-- Below are some suggestions but feel free to modify or remove them -->

        **Observed Behavior**:

        **Expected Behavior**:

        **Reproduction Steps** (Please include `ResourceGraphDefinition` and `Instances` files):

        **Versions**:
        - kro version:
        - Kubernetes Version (`kubectl version`):

        **Involved Controllers**:
        - Controller URLs and Versions (if applicable):

        **Error Logs** (if applicable)**:
        ```
        Paste any relevant logs here
        ```

        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment
  - type: dropdown
    id: issue_type
    attributes:
      label: Which option describes the most your issue?
      multiple: true
      options:
        - ResourceGraphDefinition (Create, Update, Deletion)
        - Instance (Create, Update, Deletion)
        - Directed Acyclic Graph inference
        - Common Expression Language (CEL)
        - Schema Validation
        - Others (please specify)
