apiVersion: kro.run/v1alpha1
kind: WebStack
metadata:
  name: test-app
spec:
  name: $RESOURCES_NAME
  clusterName: kro # change this value if your cluster name is not kro
  image: candonov/s3-demo-app
  s3bucket:
    enabled: true
    access: write
  ingress:
    enabled: true # this will expose unathenticated alb
  service: {}
