{{- range $name, $cluster := .Values.clusters }}
---
apiVersion: kro.run/v1alpha1
kind: EksclusterWithVpc
metadata:
  name: {{ $name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  name: {{ $name }}
  tenant: {{ $cluster.tenant | default "tenant1" | quote }}
  environment: {{ $cluster.environment | default "staging" | quote }}
  region: {{ $cluster.region | default "us-west-2" | quote }}
  k8sVersion: {{ $cluster.k8sVersion | default "1.32" | quote }}
  accountId: {{ $cluster.accountId | quote }}
  managementAccountId: {{ $cluster.managementAccountId | quote }}
  adminRoleName: {{ $cluster.adminRoleName | default "Admin" | quote }}
  fleetSecretManagerSecretNameSuffix: {{ $cluster.fleetSecretManagerSecretNameSuffix | default "argocd-secret" | quote }}
  domainName: {{ $cluster.domainName | default "" | quote }}
  workloads: {{ $cluster.workloads | default "false" | quote }}
  {{- if $cluster.subHostedZone | quote }}
  subHostedZone:
    {{- toYaml $cluster.subHostedZone | nindent 4 }}
  {{- end }}
  {{- if $cluster.cidr }}
  cidr:
    {{- toYaml $cluster.cidr | nindent 4 }}
  {{- else }}
  cidr: {}
  {{- end }}
  {{- if $cluster.gitops }}
  gitops:
    {{- toYaml $cluster.gitops | nindent 4 }}
  {{- else }}
  gitops: {}
  {{- end }}
  {{- if $cluster.addons }}
  addons:
    {{- toYaml $cluster.addons | nindent 4 }}
  {{- else }}
  addons: {}
  {{- end }}
{{- end }}