apiVersion: kro.run/v1alpha1
kind: Microservice
metadata:
  name: $CLAIM_NAME
spec:
  region: $AWS_REGION
  namePrefix: api-example
  api:
    apiName: my-api
    apiDescription: Microservice that uses Amazon API Gateway and AWS Lambda
  lambda:
    codeBucketName: $S3_BUCKET
    logicLambdaCode: microservice-business-logic.zip
    authorizerLambdaCode: microservice-authorizer.zip
    authorizerPasswordParameterARN: $SECRET_ARN
